#!/usr/bin/env bash
#
# Build vaultis and hand back a DEMO vault you can immediately open.
#
#   scripts/build.sh [--release] [--fresh] [--sample-dir DIR] [--no-sample]
#                    [--install-rust] [-- <extra cargo args>]
#
# It does three things:
#   1. Makes sure a usable RUST TOOLCHAIN is installed. If `cargo` is missing it offers
#      to install it with the official rustup installer (https://rustup.rs), asking
#      first; `--install-rust` answers yes up front, for an unattended run.
#   2. `cargo build` (debug by default, `--release` for the optimized build).
#   3. Makes sure a FULLY POPULATED sample vault exists — every tab filled in, with
#      attached documents so the encrypted volume is real — by running the
#      `seed_sample_vault` example, then prints where it is and the two passwords
#      that open it.
#
# The sample vault is fiction (see examples/seed_sample_vault.rs): fake people, fake
# institutions, visibly fake "passwords". Its two master passwords are deliberately
# trivial — `sample1` / `sample2` — because it is a throwaway demo, NOT a place to put
# anything real. It lives under `target/` so `cargo clean` takes it with it.
#
# Re-running is non-destructive: an existing sample vault is left exactly as it is (you
# may have clicked around and saved edits). Pass `--fresh` to delete and rebuild it.
set -euo pipefail

# --- The demo vault's two passwords. Demo-only, by design (see above). ---------
SAMPLE_PW1="sample1"
SAMPLE_PW2="sample2"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

profile="debug"
cargo_profile_args=()
fresh=0
sample_dir=""
extra_cargo_args=()
install_rust=0

# Oldest toolchain that can build this workspace: the crates are edition 2024 (Rust
# 1.85+) and the source uses stable let-chains (1.88+). Checked rather than assumed,
# because an old rustc fails with an error that reads like a code problem.
MIN_RUST_MINOR=88

while [[ $# -gt 0 ]]; do
    case "$1" in
        --release)
            profile="release"
            cargo_profile_args=(--release)
            shift
            ;;
        --install-rust)
            install_rust=1
            shift
            ;;
        --fresh)
            fresh=1
            shift
            ;;
        --sample-dir)
            [[ $# -ge 2 ]] || { echo "error: --sample-dir needs a DIR" >&2; exit 2; }
            sample_dir="$2"
            shift 2
            ;;
        --no-sample)
            # Build only — useful in CI, where nobody clicks around a demo vault.
            sample_dir="-"
            shift
            ;;
        --)
            shift
            extra_cargo_args=("$@")
            break
            ;;
        -h|--help)
            # Print this file's leading comment block (everything after the shebang up to
            # the first non-comment line) as the help text, so there is one description.
            awk 'NR == 1 { next } /^#/ { sub(/^# ?/, ""); print; next } { exit }' "${BASH_SOURCE[0]}"
            exit 0
            ;;
        *)
            echo "error: unknown option '$1' (see --help)" >&2
            exit 2
            ;;
    esac
done

# `${VAULTIS_SAMPLE_DIR:-}` lets the location be set from the environment too; the
# `--sample-dir` flag wins over it, and both default to target/sample-vault.
if [[ -z "$sample_dir" ]]; then
    sample_dir="${VAULTIS_SAMPLE_DIR:-$repo_root/target/sample-vault}"
fi

# --- Rust toolchain ------------------------------------------------------------
#
# Installing a compiler toolchain is a real change to the machine — it downloads and
# runs an installer from the network — so it is never done silently: the script asks,
# and defaults to NO. `--install-rust` is the explicit yes for an unattended run. On a
# machine with no terminal to ask at (a CI job, a pipe) the script prints what to run
# and stops rather than guessing.

# `cargo` on PATH, or a rustup install this shell simply has not sourced yet.
have_cargo() {
    command -v cargo >/dev/null 2>&1
}
source_cargo_env() {
    # shellcheck disable=SC1091  # generated by rustup at install time; not in the repo
    [[ -r "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
    have_cargo
}

install_rust_toolchain() {
    # Prefer rustup if it is already here (only the default toolchain is missing).
    if command -v rustup >/dev/null 2>&1; then
        echo "==> rustup is installed but no toolchain is active; installing stable"
        rustup toolchain install stable
        rustup default stable
        source_cargo_env
        return
    fi
    echo "==> Installing the Rust toolchain with rustup (https://rustup.rs)"
    # --proto '=https' --tlsv1.2 are rustup's own documented flags: refuse anything but
    # HTTPS, and refuse TLS below 1.2. `-y` accepts rustup's defaults, which include
    # putting ~/.cargo/bin on PATH for FUTURE shells; this one is fixed up below.
    if command -v curl >/dev/null 2>&1; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    elif command -v wget >/dev/null 2>&1; then
        wget --https-only -qO- https://sh.rustup.rs | sh -s -- -y
    else
        echo "error: neither curl nor wget is available to fetch the installer." >&2
        echo "       Install one of them, or install Rust yourself: https://rustup.rs" >&2
        exit 1
    fi
    source_cargo_env
}

if ! have_cargo && ! source_cargo_env; then
    echo "Rust (cargo) was not found on this machine."
    echo "vaultis is written in Rust, so a toolchain is needed to build it."
    if [[ "$install_rust" -eq 1 ]]; then
        install_rust_toolchain
    elif [[ -t 0 ]]; then
        # -t 0 = stdin is a terminal, i.e. there is somebody to answer.
        read -r -p "Install it now with rustup (from https://rustup.rs)? [y/N] " reply
        case "$reply" in
            [yY] | [yY][eE][sS]) install_rust_toolchain ;;
            *)
                echo "Not installing. Install Rust yourself and re-run this script:"
                echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
                exit 1
                ;;
        esac
    else
        echo "Re-run with --install-rust to install it automatically, or install it yourself:" >&2
        echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" >&2
        exit 1
    fi
fi

if ! have_cargo; then
    echo "error: cargo is still not on PATH after installing." >&2
    echo "       Open a new terminal (or run: source \"\$HOME/.cargo/env\") and try again." >&2
    exit 1
fi

# An ancient-but-present toolchain is the other failure mode, and its error message
# ("let chains are unstable", "edition 2024 is unsupported") reads like broken code
# rather than a stale compiler. Say so plainly instead. `cut -d. -f2` takes the minor
# version out of e.g. "rustc 1.88.0 (…)".
rust_minor="$(rustc --version 2>/dev/null | awk '{print $2}' | cut -d. -f2)"
if [[ "$rust_minor" =~ ^[0-9]+$ ]] && ((rust_minor < MIN_RUST_MINOR)); then
    echo "error: Rust 1.$rust_minor is too old to build vaultis (needs 1.$MIN_RUST_MINOR or newer)." >&2
    if command -v rustup >/dev/null 2>&1; then
        echo "       Update it with:  rustup update stable" >&2
    else
        echo "       Update your Rust installation (see https://rustup.rs)." >&2
    fi
    exit 1
fi

echo "==> Building vaultis ($profile)"
cargo build --workspace "${cargo_profile_args[@]}" "${extra_cargo_args[@]}"

if [[ "$sample_dir" == "-" ]]; then
    echo "==> Skipping the sample vault (--no-sample)"
    exit 0
fi

vault_file="$sample_dir/vault.pmv"

if [[ -e "$vault_file" && $fresh -eq 1 ]]; then
    echo "==> Removing the existing sample vault (--fresh): $sample_dir"
    rm -rf -- "$sample_dir"
fi

if [[ -e "$vault_file" ]]; then
    echo "==> Sample vault already present (left untouched; use --fresh to rebuild it)"
else
    echo "==> Seeding a fully populated sample vault"
    # The seeder is an example, so it is built on demand and never ships in a binary.
    # It refuses to overwrite an existing vault.pmv, which the check above already
    # guarantees. Key derivation uses the REAL (deliberately slow) KDF parameters, so
    # this step takes a few seconds — the demo then opens exactly as a real vault does.
    cargo run -p vaultis "${cargo_profile_args[@]}" --example seed_sample_vault -- \
        "$sample_dir" "$SAMPLE_PW1" "$SAMPLE_PW2"
fi

gui_bin="$repo_root/target/$profile/vaultis-gui"
cli_bin="$repo_root/target/$profile/vaultis"

# The summary the whole script exists for: it is the LAST thing printed, after all the
# cargo noise, so the two passwords and the location are on screen when the build ends.
cat <<EOF

────────────────────────────────────────────────────────────────────────
 Sample vault ready — fully populated demo data, safe to experiment in
────────────────────────────────────────────────────────────────────────
  Location:    $sample_dir
  Password 1:  $SAMPLE_PW1
  Password 2:  $SAMPLE_PW2

  Open it (graphical, editable):
    "$gui_bin" "$sample_dir" --write
  Open it (terminal):
    "$cli_bin" --tui "$sample_dir" --write

  Everything in it is fiction — never put real secrets in this vault.
────────────────────────────────────────────────────────────────────────
EOF
