//! vaultis-ffi — the UniFFI boundary that lets the Compose Multiplatform mobile
//! app drive the audited [`vaultis_core`] vault without reimplementing any
//! crypto, storage, or recovery logic.
//!
//! # What this crate is
//!
//! A *thin, additive* wrapper. The security-critical core (two-password Argon2id
//! KDF, XChaCha20-Poly1305, the partitioned crash-safe volume/manifest format,
//! and the corruption-fails-closed recovery) lives in `vaultis-core` and is
//! reused **verbatim**. This crate only:
//!   * holds an opaque, mutex-guarded [`OpenVault`] behind a UniFFI interface,
//!   * exposes flat value DTOs (Kotlin/Swift data classes) for the eight record
//!     types, and
//!   * maps the rich [`CoreVaultError`] down to a small, stable, **no-leak**
//!     [`VaultError`] (wrong-password and corrupt both collapse to one variant,
//!     exactly like the desktop's generic "can't open" message).
//!
//! # v1 scope — READ-ONLY
//!
//! Open with the two passwords, browse all eight tabs, view a record, read its
//! edit history. No create/edit/delete/documents/rekey yet (those are additive
//! follow-ups). A read-only open writes nothing to disk and never takes the
//! single-writer lock.
//!
//! # Security downgrade (disclosed)
//!
//! Returning a record DTO copies its fields — including a cleartext password —
//! into the JVM/Swift heap, where `ZeroizeOnDrop` cannot reach and the GC/ARC
//! may duplicate the bytes. This is an inherent, documented downgrade versus the
//! desktop. The host must minimise copies, fetch history explicitly (it can
//! contain old/new passwords), and clear clipboard/fields itself.
//!
//! The Rust side is also imperfect here, by construction: the `#[derive(uniffi::Record)]`
//! DTOs (e.g. [`Account::password`], [`Change::detail`]) and the `RustBuffer` UniFFI
//! lowers them into are NOT zeroize-on-drop. (They cannot be: UniFFI lowers a record
//! by *moving its fields out*, which Rust forbids for any type with a `Drop` impl —
//! so a `ZeroizeOnDrop` DTO would not compile.) So a `get_account`/`get_history` call
//! leaves short-lived cleartext copies in freed Rust heap in addition to the host
//! copy above. The core records themselves remain `ZeroizeOnDrop`; only these
//! boundary DTOs are exempt. Treat process memory as sensitive after a record read.

// NOTE: this crate intentionally does NOT `#![forbid(unsafe_code)]` — the UniFFI
// scaffolding generated by `setup_scaffolding!()` contains `unsafe`. The core,
// which holds all the real logic, keeps its crate-wide `forbid`.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use vaultis_core::records::{self, Record};
use vaultis_core::vault::{OpenVault, VaultError as CoreVaultError};
use zeroize::Zeroizing;

uniffi::setup_scaffolding!();

// ---------------------------------------------------------------------------
// Error: a small, stable, no-leak surface mapped from CoreVaultError.
// ---------------------------------------------------------------------------

/// Stable error surface for the mobile host. Crucially, a wrong password and a
/// corrupt/tampered vault collapse to the SAME [`VaultError::WrongPasswordOrCorrupt`]
/// variant with no detail, so the FFI never becomes a correct-password oracle —
/// mirroring the desktop's single generic failure message.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum VaultError {
    /// The two passwords were wrong, OR the vault file is corrupt/tampered. These
    /// are deliberately indistinguishable (no leak). Re-check both passwords and
    /// their order first.
    #[error("wrong passwords, or the vault is corrupt")]
    WrongPasswordOrCorrupt,
    /// No vault file exists at the given location.
    #[error("no vault found at the given location")]
    NotFound,
    /// An interrupted password change is pending; it must be finished on a
    /// writable (desktop) open before the vault can be read here.
    #[error("an interrupted password change is pending; finish it on desktop (--write)")]
    RekeyPending,
    /// Another writable session holds the vault (should not occur for read-only).
    #[error("the vault is open in another session")]
    Locked,
    /// No record with the requested id exists in that tab.
    #[error("record not found")]
    RecordNotFound,
    /// A low-level I/O error touching the vault directory.
    #[error("I/O error")]
    Io,
    /// An unexpected internal error.
    #[error("internal error")]
    Internal,
}

impl From<CoreVaultError> for VaultError {
    fn from(e: CoreVaultError) -> Self {
        match e {
            CoreVaultError::NotFound(_) => VaultError::NotFound,
            CoreVaultError::RekeyPending => VaultError::RekeyPending,
            CoreVaultError::Locked => VaultError::Locked,
            CoreVaultError::Io(_) => VaultError::Io,
            // Everything that could discriminate a wrong password from a damaged
            // vault collapses to ONE generic variant so there is no correct-password
            // oracle: the AEAD decrypt failure, bad magic/version/params, a truncated
            // file, a JSON/storage decode failure — AND `ArchiveMismatch`. The latter
            // is only reachable AFTER decrypt_with_redundancy succeeds (i.e. only with
            // the CORRECT passwords), so giving it a distinct variant let a
            // dir-write attacker turn the open into a binary correct-password oracle by
            // pre-deleting a referenced blob (audit R-3). Folding it here restores the
            // no-oracle contract. (RekeyPending is fine: it is returned BEFORE any
            // decryption, so it fires for any password and leaks nothing.)
            CoreVaultError::Crypto(_)
            | CoreVaultError::BadMagic
            | CoreVaultError::BadVersion(_)
            | CoreVaultError::Truncated
            | CoreVaultError::BadParams
            | CoreVaultError::Json(_)
            | CoreVaultError::ArchiveMismatch
            // `TooLarge` IS reachable on the open path: `read_capped_vault` rejects a
            // vault file > MAX_VAULT_SIZE BEFORE decryption. An oversize file is a
            // corruption/tamper signal, so it must collapse here too — otherwise a
            // padded vault would return a distinct `Internal`, breaking the "every open
            // failure looks identical" property (it is password-independent, so not a
            // password oracle, but folding it keeps the surface uniform).
            | CoreVaultError::TooLarge
            | CoreVaultError::Storage(_) => VaultError::WrongPasswordOrCorrupt,
            // Genuinely unreachable on a read-only open (create/write/doc-read only),
            // mapped defensively to a generic internal error.
            CoreVaultError::AlreadyExists(_)
            | CoreVaultError::ReadOnly
            | CoreVaultError::StillReferenced
            | CoreVaultError::NoSuchPartition(_) => VaultError::Internal,
        }
    }
}

// ---------------------------------------------------------------------------
// Value DTOs — flat mirrors of the eight records.rs structs (read views).
// History is NOT bundled (it can embed old/new passwords); fetch it explicitly.
// ---------------------------------------------------------------------------

/// Which tab / record collection to operate on — all EIGHT the core stores.
///
/// The v1 surface deliberately exposed only five, which silently hid three
/// collections from the mobile viewer with nothing on screen to say so. `Urgent` is
/// the worst of the three to hide: the core documents it as "Tab 0 … the most
/// time-critical things an executor must know (whom to call, where the safe key is,
/// an in-flight crisis) are the first thing seen on unlock". An executor reaching for
/// a phone in exactly that situation saw a complete-looking app with no urgent note in
/// it. Ordered to match the desktop's tab order.
#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum RecordKind {
    Urgent,
    Instruction,
    TrustWill,
    AssetLiability,
    Account,
    RealEstate,
    TaxFiling,
    GeneralDocument,
}

/// One row in a tab's master list.
#[derive(uniffi::Record)]
pub struct RecordSummary {
    pub id: String,
    /// Human label (same logic the desktop list uses).
    pub label: String,
}

/// One timestamped history / audit entry. `detail` MAY contain cleartext old/new
/// field values (including passwords) by design — gate/redact on the host.
#[derive(uniffi::Record)]
pub struct Change {
    pub at: i64,
    pub action: String,
    pub detail: String,
}

/// An URGENT note — the executor's "read this first" collection (core tab 0).
/// Field-identical to [`Instruction`], but a separate, prominent collection.
#[derive(uniffi::Record)]
pub struct Urgent {
    pub id: String,
    pub title: String,
    pub description: String,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct Instruction {
    pub id: String,
    pub title: String,
    pub description: String,
    pub created_at: i64,
    pub updated_at: i64,
}

/// One tax filing year. `documents` lists the volume file ids attached to the year;
/// the host cannot open them yet, but it MUST be able to see that they exist.
#[derive(uniffi::Record)]
pub struct TaxFiling {
    pub id: String,
    pub owner: String,
    pub year: String,
    pub notes: String,
    /// How many documents are attached (the ids themselves are not useful to the
    /// host until document export exists, but the count must not be hidden).
    pub document_count: u32,
    pub created_at: i64,
    pub updated_at: i64,
}

/// A general document entry (title + description + at most one attached file).
#[derive(uniffi::Record)]
pub struct GeneralDocument {
    pub id: String,
    pub title: String,
    pub description: String,
    /// Volume file id of the attached document, if any (opening it is post-MVP).
    pub file: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct TrustWill {
    pub id: String,
    pub document: String,
    pub usage: String,
    /// Volume file id of an attached document, if any (opening it is post-MVP).
    pub file: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct AssetLiability {
    pub id: String,
    pub kind: String,
    pub description: String,
    pub owner: String,
    pub title: String,
    pub approx_value: String,
    pub as_of_date: String,
    pub institution: String,
    pub asset_type: String,
    pub url: String,
    pub beneficiary: String,
    pub review: bool,
    pub statement: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct Account {
    pub id: String,
    pub title: String,
    pub account_type: String,
    pub account_subtype: String,
    pub owner: String,
    pub username: String,
    /// Cleartext. Crosses into the JVM/Swift heap — see the crate-level note.
    pub password: String,
    pub description: String,
    pub url: String,
    /// Date the account was closed (`YYYY-MM-DD`); blank while open.
    pub closed_as_of: String,
    pub review: bool,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct RealEstate {
    pub id: String,
    pub address: String,
    pub ownership: String,
    pub taxes: String,
    pub hoa: String,
    pub income_account: String,
    pub financing_account: String,
    pub payment_account: String,
    pub created_at: i64,
    pub updated_at: i64,
}

// --- core -> DTO mappers ---------------------------------------------------

fn map_change(c: &records::Change) -> Change {
    // Mask secret (password) before/after values via the core's audited helper, so the
    // FFI never ships cleartext old/new passwords across the boundary. `detail` for a
    // password field is `password: "old" -> "new"`; `display_detail` rewrites it to
    // `password: <hidden> -> <hidden>` and passes every non-secret detail through
    // unchanged (audit-log entries hold no passwords, so this is a no-op for them).
    Change { at: c.at, action: c.action.clone(), detail: records::display_detail(&c.detail) }
}

fn map_urgent(r: &records::Urgent) -> Urgent {
    Urgent {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_instruction(r: &records::Instruction) -> Instruction {
    Instruction {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_tax_filing(r: &records::TaxFiling) -> TaxFiling {
    TaxFiling {
        id: r.id.clone(),
        owner: r.owner.clone(),
        year: r.year.clone(),
        notes: r.notes.clone(),
        // `as u32` is safe: the document count is bounded by the store's own caps,
        // far below u32::MAX, and a saturating cast keeps a corrupt count from wrapping.
        document_count: u32::try_from(r.documents.len()).unwrap_or(u32::MAX),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_general_document(r: &records::GeneralDocument) -> GeneralDocument {
    GeneralDocument {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        file: r.file.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_trust_will(r: &records::TrustWill) -> TrustWill {
    TrustWill {
        id: r.id.clone(),
        document: r.document.clone(),
        usage: r.usage.clone(),
        file: r.file.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_asset(r: &records::AssetLiability) -> AssetLiability {
    AssetLiability {
        id: r.id.clone(),
        kind: r.kind.clone(),
        description: r.description.clone(),
        owner: r.owner.clone(),
        title: r.title.clone(),
        approx_value: r.approx_value.clone(),
        as_of_date: r.as_of_date.clone(),
        institution: r.institution.clone(),
        asset_type: r.asset_type.clone(),
        url: r.url.clone(),
        beneficiary: r.beneficiary.clone(),
        review: r.review,
        statement: r.statement.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_account(r: &records::Account) -> Account {
    Account {
        id: r.id.clone(),
        title: r.title.clone(),
        account_type: r.account_type.clone(),
        account_subtype: r.account_subtype.clone(),
        owner: r.owner.clone(),
        username: r.username.clone(),
        password: r.password.clone(),
        description: r.description.clone(),
        url: r.url.clone(),
        closed_as_of: r.closed_as_of.clone(),
        review: r.review,
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_real_estate(r: &records::RealEstate) -> RealEstate {
    RealEstate {
        id: r.id.clone(),
        address: r.address.clone(),
        ownership: r.owner.clone(),
        taxes: r.taxes.clone(),
        hoa: r.hoa.clone(),
        income_account: r.income_account.clone(),
        financing_account: r.financing_account.clone(),
        payment_account: r.payment_account.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

// ---------------------------------------------------------------------------
// The opaque unlocked-vault handle.
// ---------------------------------------------------------------------------

/// An unlocked vault. Opaque to the host: the derived key never crosses the FFI.
/// Wraps the core [`OpenVault`] behind a mutex so the host can hold exactly one
/// handle and every call is serialised (this stands in for the desktop's
/// cross-process single-writer file lock, which a single app process doesn't
/// need). Dropping the handle runs the core's zeroize-on-drop.
#[derive(uniffi::Object)]
pub struct Vault {
    inner: Mutex<OpenVault>,
}

/// Open an existing vault **read-only** with the two passwords, in order.
///
/// `dir` is the app-private directory that holds `vault.pmv` (+ `manifest/`,
/// `volume/`) — the host hands in its sandbox path; arbitrary user paths are not
/// accepted. `pw1`/`pw2` are the raw password bytes. UniFFI lowers the host's
/// ByteArray/Data into Rust-OWNED `Vec<u8>` copies, so this function wipes them
/// before returning — on success, on the error path, AND on an unwind if the open
/// path ever panics; the host should still overwrite its own copies afterwards.
#[uniffi::export]
pub fn open_vault(dir: String, pw1: Vec<u8>, pw2: Vec<u8>) -> Result<Arc<Vault>, VaultError> {
    // Bind the host-owned plaintext copies in `Zeroizing` so they are wiped on EVERY
    // exit, including a panic-unwind. A plain `.zeroize()` AFTER the open call is
    // skipped by unwinding, which would strand the master passwords in freed heap.
    let pw1 = Zeroizing::new(pw1);
    let pw2 = Zeroizing::new(pw2);
    let path = PathBuf::from(dir).join("vault.pmv");
    let opened = OpenVault::open_read_only(path, &pw1, &pw2)?;
    Ok(Arc::new(Vault { inner: Mutex::new(opened) }))
}

#[uniffi::export]
impl Vault {
    /// Human-readable notice if the live `vault.pmv` was unreadable and the vault
    /// was recovered from an in-place redundant copy (a roll-forward/rollback);
    /// `None` on a normal open. Surface it so the user is rollback-aware.
    pub fn recovery_notice(&self) -> Option<String> {
        self.lock().recovery_notice().map(|s| s.to_string())
    }

    /// The monotonic write counter of the snapshot just opened. A surprise drop
    /// versus a remembered value signals a whole-file rollback to an older copy.
    pub fn generation(&self) -> u64 {
        self.lock().opened_generation()
    }

    /// Unix-seconds timestamp the vault was previously opened (0 if never).
    pub fn previous_access(&self) -> i64 {
        self.lock().previous_access()
    }

    /// [`Vault::previous_access`] rendered exactly like the desktop's `format_time`:
    /// `YYYY-MM-DD HH:MM:SS UTC`, or `"never"` for a zero/negative stamp.
    ///
    /// The host shows this on unlock so an access the user does not recognise is
    /// visible — the same unauthorised-open signal both desktop front-ends print
    /// ("Unlocked. Last opened: … (generation N)"). Formatting lives here, not in
    /// Kotlin/Swift, so the (fiddly) calendar math stays in the one audited
    /// implementation (`vaultis_core::records::civil_from_unix`) and cannot drift
    /// between the desktop and the two mobile front-ends.
    pub fn previous_access_label(&self) -> String {
        format_time(self.lock().previous_access())
    }

    /// The master list for one tab: `{id, label}` per record, in stored order.
    pub fn list_records(&self, kind: RecordKind) -> Vec<RecordSummary> {
        let ov = self.lock();
        let v = &ov.vault;
        match kind {
            RecordKind::Urgent => v.urgent.iter().map(summary).collect(),
            RecordKind::Instruction => v.instructions.iter().map(summary).collect(),
            RecordKind::TrustWill => v.trust_wills.iter().map(summary).collect(),
            RecordKind::AssetLiability => v.assets.iter().map(summary).collect(),
            RecordKind::Account => v.accounts.iter().map(summary).collect(),
            RecordKind::RealEstate => v.real_estate.iter().map(summary).collect(),
            RecordKind::TaxFiling => v.tax_filings.iter().map(summary).collect(),
            RecordKind::GeneralDocument => v.general_documents.iter().map(summary).collect(),
        }
    }

    /// How many records are in a tab (cheap, no cleartext crosses the boundary).
    pub fn count(&self, kind: RecordKind) -> u32 {
        let ov = self.lock();
        let v = &ov.vault;
        let n = match kind {
            RecordKind::Urgent => v.urgent.len(),
            RecordKind::Instruction => v.instructions.len(),
            RecordKind::TrustWill => v.trust_wills.len(),
            RecordKind::AssetLiability => v.assets.len(),
            RecordKind::Account => v.accounts.len(),
            RecordKind::RealEstate => v.real_estate.len(),
            RecordKind::TaxFiling => v.tax_filings.len(),
            RecordKind::GeneralDocument => v.general_documents.len(),
        };
        n as u32
    }

    pub fn get_urgent(&self, id: String) -> Result<Urgent, VaultError> {
        let ov = self.lock();
        ov.vault
            .urgent
            .iter()
            .find(|r| r.id == id)
            .map(map_urgent)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_instruction(&self, id: String) -> Result<Instruction, VaultError> {
        let ov = self.lock();
        ov.vault
            .instructions
            .iter()
            .find(|r| r.id == id)
            .map(map_instruction)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_tax_filing(&self, id: String) -> Result<TaxFiling, VaultError> {
        let ov = self.lock();
        ov.vault
            .tax_filings
            .iter()
            .find(|r| r.id == id)
            .map(map_tax_filing)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_general_document(&self, id: String) -> Result<GeneralDocument, VaultError> {
        let ov = self.lock();
        ov.vault
            .general_documents
            .iter()
            .find(|r| r.id == id)
            .map(map_general_document)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_trust_will(&self, id: String) -> Result<TrustWill, VaultError> {
        let ov = self.lock();
        ov.vault
            .trust_wills
            .iter()
            .find(|r| r.id == id)
            .map(map_trust_will)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_asset(&self, id: String) -> Result<AssetLiability, VaultError> {
        let ov = self.lock();
        ov.vault
            .assets
            .iter()
            .find(|r| r.id == id)
            .map(map_asset)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_account(&self, id: String) -> Result<Account, VaultError> {
        let ov = self.lock();
        ov.vault
            .accounts
            .iter()
            .find(|r| r.id == id)
            .map(map_account)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_real_estate(&self, id: String) -> Result<RealEstate, VaultError> {
        let ov = self.lock();
        ov.vault
            .real_estate
            .iter()
            .find(|r| r.id == id)
            .map(map_real_estate)
            .ok_or(VaultError::RecordNotFound)
    }

    /// A record's edit history, newest concerns last. Fetched explicitly (never bundled
    /// into the record DTO). Secret (password) before/after values are MASKED here via
    /// the core's `display_detail` (see `map_change`), so no cleartext password ever
    /// crosses the FFI boundary; the host may still choose to gate the whole history.
    pub fn get_history(&self, kind: RecordKind, id: String) -> Result<Vec<Change>, VaultError> {
        let ov = self.lock();
        let v = &ov.vault;
        let history = match kind {
            RecordKind::Urgent => v.urgent.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::Instruction => v.instructions.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::TrustWill => v.trust_wills.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::AssetLiability => v.assets.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::Account => v.accounts.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::RealEstate => v.real_estate.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::TaxFiling => v.tax_filings.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::GeneralDocument => v.general_documents.iter().find(|r| r.id == id).map(|r| &r.history),
        };
        history
            .map(|h| h.iter().map(map_change).collect())
            .ok_or(VaultError::RecordNotFound)
    }

    /// The vault-wide audit log (created/deleted/opened/compacted events).
    pub fn audit_log(&self) -> Vec<Change> {
        self.lock().vault.audit.iter().map(map_change).collect()
    }
}

impl Vault {
    /// Lock the inner handle, recovering from a poisoned mutex (a panic in a
    /// previous call) by taking the guard anyway — the core data is still valid
    /// and there is only one handle, so there is nothing to corrupt.
    fn lock(&self) -> std::sync::MutexGuard<'_, OpenVault> {
        self.inner.lock().unwrap_or_else(|p| p.into_inner())
    }
}

fn summary<R: Record>(r: &R) -> RecordSummary {
    RecordSummary { id: r.id().to_string(), label: r.label() }
}

/// Format a unix-seconds timestamp as `YYYY-MM-DD HH:MM:SS UTC`, or `"never"` for a
/// zero/negative stamp. Byte-for-byte the desktop's `format_time` (vaultis-desktop
/// `ui.rs`), including the shared `civil_from_unix` calendar math, so the "last
/// opened" line the mobile host shows is identical to the desktop's.
fn format_time(ts: i64) -> String {
    if ts <= 0 {
        return "never".to_string();
    }
    let (year, mo, d, h, m, s) = records::civil_from_unix(ts);
    format!("{year:04}-{mo:02}-{d:02} {h:02}:{m:02}:{s:02} UTC")
}

// ---------------------------------------------------------------------------
// Host-side tests: drive the FFI surface against a real vault built with the
// core (no Android/iOS toolchain needed). Verifies open/list/get/history + the
// no-leak error mapping.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    /// v1 FFI SURFACE LOCK (compile-time). The mobile bindings are generated against this
    /// crate's `#[uniffi::export]` surface and `App.kt` hardcodes these names, so an
    /// accidental rename, removal, field change, or enum-variant change must break the
    /// build. This test pins the surface by EXHAUSTIVELY matching every enum variant and
    /// constructing every DTO with ALL its fields — any change is a COMPILE error here.
    /// (cargo-public-api was deliberately not used: on a UniFFI crate its output is ~90%
    /// `FfiConverter`/`Lift`/`Lower` boilerplate that churns on every uniffi bump, and it
    /// cannot see a dropped `#[uniffi::export]`; the android APK job is the cross-language
    /// backstop that compiles `App.kt` against the generated bindings.)
    #[test]
    fn v1_ffi_surface_is_locked() {
        // Every RecordKind variant — a new/removed/renamed variant breaks this match.
        fn kind_name(k: RecordKind) -> &'static str {
            match k {
                RecordKind::Urgent => "Urgent",
                RecordKind::Instruction => "Instruction",
                RecordKind::TrustWill => "TrustWill",
                RecordKind::AssetLiability => "AssetLiability",
                RecordKind::Account => "Account",
                RecordKind::RealEstate => "RealEstate",
                RecordKind::TaxFiling => "TaxFiling",
                RecordKind::GeneralDocument => "GeneralDocument",
            }
        }
        for k in [
            RecordKind::Urgent,
            RecordKind::Instruction,
            RecordKind::TrustWill,
            RecordKind::AssetLiability,
            RecordKind::Account,
            RecordKind::RealEstate,
            RecordKind::TaxFiling,
            RecordKind::GeneralDocument,
        ] {
            assert!(!kind_name(k).is_empty());
        }

        // Every VaultError variant — the exhaustive match pins the no-leak error surface.
        fn err_is_known(e: &VaultError) -> bool {
            match e {
                VaultError::WrongPasswordOrCorrupt
                | VaultError::NotFound
                | VaultError::RekeyPending
                | VaultError::Locked
                | VaultError::RecordNotFound
                | VaultError::Io
                | VaultError::Internal => true,
            }
        }
        assert!(err_is_known(&VaultError::WrongPasswordOrCorrupt));

        // Every DTO with ALL its fields — a renamed/removed/added field breaks these literals.
        let _ = RecordSummary { id: String::new(), label: String::new() };
        let _ = Change { at: 0, action: String::new(), detail: String::new() };
        let _ = Instruction {
            id: String::new(),
            title: String::new(),
            description: String::new(),
            created_at: 0,
            updated_at: 0,
        };
        let _ = TrustWill {
            id: String::new(),
            document: String::new(),
            usage: String::new(),
            file: None,
            created_at: 0,
            updated_at: 0,
        };
        let _ = AssetLiability {
            id: String::new(),
            kind: String::new(),
            description: String::new(),
            owner: String::new(),
            title: String::new(),
            approx_value: String::new(),
            as_of_date: String::new(),
            institution: String::new(),
            asset_type: String::new(),
            url: String::new(),
            beneficiary: String::new(),
            review: false,
            statement: None,
            created_at: 0,
            updated_at: 0,
        };
        let _ = Account {
            id: String::new(),
            title: String::new(),
            account_type: String::new(),
            account_subtype: String::new(),
            owner: String::new(),
            username: String::new(),
            password: String::new(),
            description: String::new(),
            url: String::new(),
            closed_as_of: String::new(),
            review: false,
            created_at: 0,
            updated_at: 0,
        };
        let _ = RealEstate {
            id: String::new(),
            address: String::new(),
            ownership: String::new(),
            taxes: String::new(),
            hoa: String::new(),
            income_account: String::new(),
            financing_account: String::new(),
            payment_account: String::new(),
            created_at: 0,
            updated_at: 0,
        };

        // The exported entry point keeps its exact signature (referenced, not called).
        // The explicit fn-pointer type IS the lock here, so the complexity is intentional.
        #[allow(clippy::type_complexity)]
        let _open: fn(String, Vec<u8>, Vec<u8>) -> Result<std::sync::Arc<Vault>, VaultError> = open_vault;
    }

    // -----------------------------------------------------------------------
    // Extended FFI coverage: build a vault with one of EACH of the EIGHT record
    // types via the core, then drive every read-only FFI method. All eight are now
    // surfaced — the five-kind v1 surface silently hid Urgent, tax filings and general
    // documents from the mobile viewer. The EXPANDED RealEstate portal fields are still
    // deliberately not mapped; see `real_estate_with_new_fields_maps_only_v1_fields`.
    // -----------------------------------------------------------------------

    struct Ids {
        urgent: String,
        ins: String,
        tw: String,
        asset: String,
        acc: String,
        re: String,
        tax: String,
        gendoc: String,
    }

    /// Write a small throwaway source file (so `add_document` can ingest it).
    fn write_src(dir: &std::path::Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
        let p = dir.join(name);
        std::fs::write(&p, bytes).unwrap();
        p
    }

    fn make_full_vault(dir: &std::path::Path, pw1: &[u8], pw2: &[u8]) -> Ids {
        let path = dir.join("vault.pmv");
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        let mut ov = OpenVault::create(path, pw1, pw2, params).unwrap();

        // An URGENT note — the executor's "read this first" record (core tab 0).
        let mut urgent = records::Urgent::new().unwrap();
        urgent.title = "Call the lawyer first".into();
        urgent.description = "Ring Pat Okafor on 555-0101 before touching anything.".into();
        let urgent_id = urgent.id.clone();
        records::upsert(&mut ov.vault.urgent, urgent);

        let mut ins = records::Instruction::new().unwrap();
        ins.title = "Funeral wishes".into();
        ins.description = "Cremation, no service.".into();
        let ins_id = ins.id.clone();
        records::upsert(&mut ov.vault.instructions, ins);

        // Upload real documents so the records' doc-reference fields point at
        // blobs that actually exist (the open-time referenced⊆stored check
        // would otherwise fail with ArchiveMismatch).
        let trust_src = write_src(dir, "trust.pdf", b"trust document bytes");
        let trust_blob = ov.add_document("trust-wills", "trust.pdf", &trust_src).unwrap();

        let mut tw = records::TrustWill::new().unwrap();
        tw.document = "Living Trust".into();
        tw.usage = "Held at the law office.".into();
        tw.file = Some(trust_blob);
        let tw_id = tw.id.clone();
        records::upsert(&mut ov.vault.trust_wills, tw);

        let stmt_src = write_src(dir, "stmt.pdf", b"statement bytes");
        let stmt_blob = ov.add_document("assets", "stmt.pdf", &stmt_src).unwrap();

        let mut al = records::AssetLiability::new().unwrap();
        al.kind = "Liability".into();
        al.description = "Mortgage".into();
        al.owner = "Jane".into();
        al.approx_value = "250000".into();
        al.as_of_date = "2026-01-01".into();
        al.institution = "Big Bank".into();
        al.asset_type = "Real Estate Loan".into();
        al.url = "https://bank.example".into();
        al.beneficiary = "Spouse".into();
        al.review = true;
        al.statement = Some(stmt_blob);
        let al_id = al.id.clone();
        records::upsert(&mut ov.vault.assets, al);

        let mut acc = records::Account::new().unwrap();
        acc.account_type = "Financial".into();
        acc.account_subtype = "IRA".into();
        acc.owner = "Jane".into();
        acc.username = "alice".into();
        acc.password = "s3cret".into();
        acc.description = "Retirement".into();
        acc.url = "https://broker.example".into();
        acc.closed_as_of = "2026-06-18".into();
        acc.review = true;
        let acc_id = acc.id.clone();
        records::upsert(&mut ov.vault.accounts, acc);

        // RealEstate with the EXPANDED fields populated (portals, balance,
        // comments, documents). Only the original fields are mapped by the FFI.
        let re_loc = records::real_estate_doc_location("123 Main St");
        let deed_src = write_src(dir, "deed.pdf", b"deed bytes");
        let deed_blob = ov.add_document(&re_loc, "deed.pdf", &deed_src).unwrap();
        let policy_src = write_src(dir, "policy.pdf", b"policy bytes");
        let policy_blob = ov.add_document(&re_loc, "policy.pdf", &policy_src).unwrap();

        let mut re = records::RealEstate::new().unwrap();
        re.address = "123 Main St".into();
        re.owner = "Joint".into();
        re.taxes = "6000/yr".into();
        re.hoa = "Sunset HOA".into();
        re.income_account = "rent-acct".into();
        re.financing_account = "loan-acct".into();
        re.payment_account = "checking".into();
        re.financing_balance = "199000".into();
        re.property_mgmt_url = "https://pm.example".into();
        re.property_mgmt_username = "pmuser".into();
        re.property_mgmt_password = "pmpass".into();
        re.insurance_url = "https://ins.example".into();
        re.insurance_username = "insuser".into();
        re.insurance_password = "inspass".into();
        re.hoa_url = "https://hoa.example".into();
        re.hoa_username = "hoauser".into();
        re.hoa_password = "hoapass".into();
        re.comments = "Tenant occupied.".into();
        re.documents = vec![deed_blob, policy_blob];
        let re_id = re.id.clone();
        records::upsert(&mut ov.vault.real_estate, re);

        // A tax filing — present in the vault AND now exposed by the FFI.
        let tax_loc = records::tax_doc_location("2024");
        let tax_src = write_src(dir, "1040.pdf", b"1040 bytes");
        let tax_blob = ov.add_document(&tax_loc, "1040.pdf", &tax_src).unwrap();

        let mut tax = records::TaxFiling::new().unwrap();
        tax.year = "2024".into();
        tax.notes = "Filed on time.".into();
        tax.documents = vec![tax_blob];
        let tax_id = tax.id.clone();
        records::upsert(&mut ov.vault.tax_filings, tax);

        // A general document entry with a real attached blob.
        let gd_src = write_src(dir, "passport.pdf", b"passport scan bytes");
        let gd_blob = ov.add_document("general", "passport.pdf", &gd_src).unwrap();
        let mut gd = records::GeneralDocument::new().unwrap();
        gd.title = "Passport".into();
        gd.description = "Scan of Jane's passport.".into();
        gd.file = Some(gd_blob);
        let gd_id = gd.id.clone();
        records::upsert(&mut ov.vault.general_documents, gd);

        ov.save().unwrap();
        Ids {
            urgent: urgent_id,
            ins: ins_id,
            tw: tw_id,
            asset: al_id,
            acc: acc_id,
            re: re_id,
            tax: tax_id,
            gendoc: gd_id,
        }
    }

    fn open_full(dir: &std::path::Path) -> Arc<Vault> {
        open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .expect("opens with correct passwords")
    }

    fn open_full_dir(dir: &std::path::Path, pw1: &[u8], pw2: &[u8]) -> Arc<Vault> {
        open_vault(dir.to_str().unwrap().to_string(), pw1.to_vec(), pw2.to_vec())
            .expect("opens with correct passwords")
    }

    #[test]
    fn count_for_every_kind() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert_eq!(v.count(RecordKind::Instruction), 1);
        assert_eq!(v.count(RecordKind::TrustWill), 1);
        assert_eq!(v.count(RecordKind::AssetLiability), 1);
        assert_eq!(v.count(RecordKind::Account), 1);
        assert_eq!(v.count(RecordKind::RealEstate), 1);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn list_records_for_every_kind_has_labels() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        for (kind, want_id, want_label) in [
            (RecordKind::Instruction, &ids.ins, "Funeral wishes"),
            (RecordKind::TrustWill, &ids.tw, "Living Trust"),
            (RecordKind::AssetLiability, &ids.asset, "[Liability] Mortgage"),
            (RecordKind::Account, &ids.acc, "Financial - alice"),
            (RecordKind::RealEstate, &ids.re, "123 Main St"),
        ] {
            let rows = v.list_records(kind);
            assert_eq!(rows.len(), 1, "exactly one row for {kind:?}");
            assert_eq!(&rows[0].id, want_id, "id matches for {kind:?}");
            assert_eq!(rows[0].label, want_label, "label matches for {kind:?}");
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_instruction_maps_all_fields() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let r = v.get_instruction(ids.ins.clone()).unwrap();
        assert_eq!(r.id, ids.ins);
        assert_eq!(r.title, "Funeral wishes");
        assert_eq!(r.description, "Cremation, no service.");
        assert!(r.created_at > 0);
        assert_eq!(r.created_at, r.updated_at, "created on insert == updated");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_trust_will_maps_all_fields_including_file() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let r = v.get_trust_will(ids.tw.clone()).unwrap();
        assert_eq!(r.id, ids.tw);
        assert_eq!(r.document, "Living Trust");
        assert_eq!(r.usage, "Held at the law office.");
        assert!(r.file.is_some(), "attached file id is surfaced");
        assert_eq!(r.file.as_ref().unwrap().len(), 32, "blob id is a 128-bit hex id");
        assert!(r.created_at > 0 && r.updated_at > 0);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_asset_maps_all_fields() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let r = v.get_asset(ids.asset.clone()).unwrap();
        assert_eq!(r.id, ids.asset);
        assert_eq!(r.kind, "Liability");
        assert_eq!(r.description, "Mortgage");
        assert_eq!(r.owner, "Jane");
        assert_eq!(r.approx_value, "250000");
        assert_eq!(r.as_of_date, "2026-01-01");
        assert_eq!(r.institution, "Big Bank");
        assert_eq!(r.asset_type, "Real Estate Loan");
        assert_eq!(r.url, "https://bank.example");
        assert_eq!(r.beneficiary, "Spouse");
        assert!(r.review);
        assert!(r.statement.is_some(), "attached statement id is surfaced");
        assert_eq!(r.statement.as_ref().unwrap().len(), 32, "blob id is a 128-bit hex id");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_account_maps_all_fields_including_cleartext_password() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let r = v.get_account(ids.acc.clone()).unwrap();
        assert_eq!(r.id, ids.acc);
        assert_eq!(r.account_type, "Financial");
        assert_eq!(r.account_subtype, "IRA");
        assert_eq!(r.owner, "Jane");
        assert_eq!(r.username, "alice");
        assert_eq!(r.password, "s3cret");
        assert_eq!(r.description, "Retirement");
        assert_eq!(r.url, "https://broker.example");
        assert_eq!(r.closed_as_of, "2026-06-18");
        assert!(r.review);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_real_estate_maps_the_original_v1_fields() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let r = v.get_real_estate(ids.re.clone()).unwrap();
        assert_eq!(r.id, ids.re);
        assert_eq!(r.address, "123 Main St");
        assert_eq!(r.ownership, "Joint");
        assert_eq!(r.taxes, "6000/yr");
        assert_eq!(r.hoa, "Sunset HOA");
        assert_eq!(r.income_account, "rent-acct");
        assert_eq!(r.financing_account, "loan-acct");
        assert_eq!(r.payment_account, "checking");
        assert!(r.created_at > 0 && r.updated_at > 0);
        std::fs::remove_dir_all(&dir).ok();
    }

    /// Forward-compat: a RealEstate record whose NEW expanded fields (portals,
    /// financing_balance, comments, documents) are all populated must still map
    /// cleanly through the v1 DTO — the FFI maps only the original fields and
    /// silently ignores the new ones (it does not panic, drop the record, or
    /// fail to find it).
    #[test]
    fn real_estate_with_new_fields_maps_only_v1_fields() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);

        let rows = v.list_records(RecordKind::RealEstate);
        assert_eq!(rows.len(), 1);
        let r = v.get_real_estate(ids.re.clone()).expect("RE with new fields still maps");

        assert_eq!(r.address, "123 Main St");
        assert_eq!(r.financing_account, "loan-acct");
        // The DTO's field set is exactly the original ones — constructing this
        // literal would fail to compile if a new field had leaked in.
        let _exhaustive_v1_shape = RealEstate {
            id: r.id.clone(),
            address: r.address.clone(),
            ownership: r.ownership.clone(),
            taxes: r.taxes.clone(),
            hoa: r.hoa.clone(),
            income_account: r.income_account.clone(),
            financing_account: r.financing_account.clone(),
            payment_account: r.payment_account.clone(),
            created_at: r.created_at,
            updated_at: r.updated_at,
        };
        std::fs::remove_dir_all(&dir).ok();
    }

    /// Taxes and the new RealEstate portal fields are intentionally NOT exposed
    /// by the read-only v1 FFI: there is no RecordKind for taxes and no getter
    /// for a tax filing, so the tax filing — though present in the vault — is
    /// unreachable through the FFI surface.
    #[test]
    fn full_vault_exposes_only_v1_surface() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);

        // EVERY collection the core stores must be reachable. A kind missing here is a
        // collection the phone silently hides from an executor — which is exactly the
        // defect this covers: `Urgent` is the vault's "read this first" tab.
        for kind in [
            RecordKind::Urgent,
            RecordKind::Instruction,
            RecordKind::TrustWill,
            RecordKind::AssetLiability,
            RecordKind::Account,
            RecordKind::RealEstate,
            RecordKind::TaxFiling,
            RecordKind::GeneralDocument,
        ] {
            assert_eq!(v.count(kind), 1, "{kind:?} present");
            assert_eq!(v.list_records(kind).len(), 1, "{kind:?} listed");
            assert!(!v.list_records(kind)[0].label.is_empty(), "{kind:?} has a list label");
        }

        // The urgent note's actual CONTENT reaches the host, not just its count.
        let urgent = v.get_urgent(ids.urgent.clone()).expect("urgent note is readable");
        assert_eq!(urgent.title, "Call the lawyer first");
        assert!(urgent.description.contains("555-0101"));

        // Tax filings expose the attached-document COUNT, so an executor can at least
        // see that documents exist for a year even though opening them is post-MVP.
        let tax = v.get_tax_filing(ids.tax.clone()).expect("tax filing is readable");
        assert_eq!(tax.year, "2024");
        assert_eq!(tax.document_count, 1);

        let gd = v.get_general_document(ids.gendoc.clone()).expect("general doc is readable");
        assert_eq!(gd.title, "Passport");
        assert!(gd.file.is_some(), "the attached blob is visible to the host");

        assert!(matches!(v.get_instruction(ids.tax.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_trust_will(ids.tax.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_asset(ids.tax.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_account(ids.tax.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_real_estate(ids.tax.clone()), Err(VaultError::RecordNotFound)));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_history_for_every_kind_has_created_entry() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        for (kind, id) in [
            (RecordKind::Urgent, &ids.urgent),
            (RecordKind::Instruction, &ids.ins),
            (RecordKind::TrustWill, &ids.tw),
            (RecordKind::AssetLiability, &ids.asset),
            (RecordKind::Account, &ids.acc),
            (RecordKind::RealEstate, &ids.re),
            (RecordKind::TaxFiling, &ids.tax),
            (RecordKind::GeneralDocument, &ids.gendoc),
        ] {
            let hist = v.get_history(kind, id.clone()).unwrap();
            assert!(!hist.is_empty(), "history present for {kind:?}");
            assert!(hist.iter().any(|c| c.action == "created"), "a 'created' entry for {kind:?}");
            for c in &hist {
                assert!(c.at > 0, "history entries are timestamped for {kind:?}");
            }
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_history_records_edits_with_field_detail() {
        let dir = tmp();
        let path = dir.join("vault.pmv");
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        let mut ov = OpenVault::create(path, b"one", b"two", params).unwrap();
        let mut acc = records::Account::new().unwrap();
        acc.account_type = "Financial".into();
        acc.username = "alice".into();
        acc.password = "old".into();
        let id = acc.id.clone();
        records::upsert(&mut ov.vault.accounts, acc);
        let mut edit = ov.vault.accounts[0].clone();
        edit.password = "new".into();
        records::upsert(&mut ov.vault.accounts, edit);
        ov.save().unwrap();
        drop(ov);

        let v = open_full_dir(&dir, b"one", b"two");
        let hist = v.get_history(RecordKind::Account, id).unwrap();
        assert!(hist.iter().any(|c| c.action == "created"));
        let pw_edit = hist
            .iter()
            .find(|c| c.action == "updated" && c.detail.contains("password"))
            .expect("the password edit is in history");
        // The cleartext old/new values must be MASKED across the FFI boundary.
        assert!(pw_edit.detail.contains("<hidden>"), "secret values masked: {}", pw_edit.detail);
        assert!(
            !pw_edit.detail.contains("\"old\"") && !pw_edit.detail.contains("\"new\""),
            "no cleartext password leaks through get_history: {}",
            pw_edit.detail
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn get_history_bogus_id_is_record_not_found() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        for kind in [
            RecordKind::Urgent,
            RecordKind::Instruction,
            RecordKind::TrustWill,
            RecordKind::AssetLiability,
            RecordKind::Account,
            RecordKind::RealEstate,
            RecordKind::TaxFiling,
            RecordKind::GeneralDocument,
        ] {
            assert!(matches!(
                v.get_history(kind, "no-such-id".to_string()),
                Err(VaultError::RecordNotFound)
            ));
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn every_typed_getter_rejects_a_bogus_id() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert!(matches!(v.get_instruction("x".into()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_trust_will("x".into()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_asset("x".into()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_account("x".into()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_real_estate("x".into()), Err(VaultError::RecordNotFound)));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn typed_getters_are_kind_scoped() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert!(matches!(v.get_instruction(ids.acc.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_trust_will(ids.acc.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_asset(ids.acc.clone()), Err(VaultError::RecordNotFound)));
        assert!(matches!(v.get_real_estate(ids.acc.clone()), Err(VaultError::RecordNotFound)));
        assert!(v.get_account(ids.acc.clone()).is_ok());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn audit_log_has_vault_created_and_no_open_event() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let audit = v.audit_log();
        assert!(audit.iter().any(|c| c.action == "vault_created"), "vault_created event present");
        for c in &audit {
            assert!(c.at > 0, "audit entries are timestamped");
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn recovery_notice_is_none_on_normal_open() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert!(v.recovery_notice().is_none(), "no recovery on a clean open");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn generation_and_previous_access_reflect_the_saved_snapshot() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert!(v.generation() >= 1, "opened generation is the saved counter");
        assert!(v.previous_access() > 0, "previous access is a real timestamp");
        std::fs::remove_dir_all(&dir).ok();
    }

    /// The host renders the "last opened" line from this label, so it must be the
    /// desktop's exact `YYYY-MM-DD HH:MM:SS UTC` shape (not a locale/timezone-dependent
    /// one) and must agree with the raw timestamp it formats.
    #[test]
    fn previous_access_label_matches_the_desktop_format() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let label = v.previous_access_label();
        assert_eq!(label, format_time(v.previous_access()), "label formats the real stamp");
        assert!(label.ends_with(" UTC"), "explicit UTC, never local time: {label}");
        // "YYYY-MM-DD HH:MM:SS UTC" — fixed width, so a shape regression is caught.
        assert_eq!(label.len(), 23, "unexpected shape: {label}");
        let (date, rest) = label.split_once(' ').expect("date and time are space-separated");
        assert_eq!(date.len(), 10, "YYYY-MM-DD");
        assert_eq!(date.matches('-').count(), 2, "YYYY-MM-DD");
        assert_eq!(rest.matches(':').count(), 2, "HH:MM:SS");
        std::fs::remove_dir_all(&dir).ok();
    }

    /// COMPILE-TIME DRIFT GUARD — the fix for the defect where the mobile viewer showed
    /// five of the core's eight record collections and silently hid `Urgent`, tax filings
    /// and general documents from an executor.
    ///
    /// The destructure below is **exhaustive on purpose**: no `..` rest pattern. Adding a
    /// field to `records::Vault` therefore makes this test fail to COMPILE, forcing whoever
    /// adds it to come here and answer the question that was never asked last time: *is this
    /// a record collection an executor must be able to read on their phone?* If it is, it
    /// needs a `RecordKind`, a DTO, a getter and a tab — and the loop below then proves the
    /// FFI actually reports it.
    ///
    /// Do not "fix" a compile failure here by adding `..`; that deletes the guard.
    #[test]
    fn every_core_record_collection_is_reachable_through_the_ffi() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        let ov = v.lock();

        let records::Vault {
            // --- the record collections: each MUST have a RecordKind ------------------
            urgent,
            instructions,
            trust_wills,
            assets,
            accounts,
            real_estate,
            tax_filings,
            general_documents,
            // --- everything else: metadata, not user-visible record collections -------
            version: _,
            generation: _,
            last_opened_at: _,
            id: _,
            settings: _,
            audit: _,
            deleted_docs: _,
            categories: _,
        } = &ov.vault;

        // Snapshot the true lengths while the guard is held...
        let expected = [
            ("urgent", urgent.len(), RecordKind::Urgent),
            ("instructions", instructions.len(), RecordKind::Instruction),
            ("trust_wills", trust_wills.len(), RecordKind::TrustWill),
            ("assets", assets.len(), RecordKind::AssetLiability),
            ("accounts", accounts.len(), RecordKind::Account),
            ("real_estate", real_estate.len(), RecordKind::RealEstate),
            ("tax_filings", tax_filings.len(), RecordKind::TaxFiling),
            ("general_documents", general_documents.len(), RecordKind::GeneralDocument),
        ];
        // ...then RELEASE it before touching the FFI. `Vault::count` takes the very same
        // std::sync::Mutex, which is NOT reentrant, so querying it while still holding the
        // guard would deadlock this test rather than fail it.
        drop(ov);

        // Every collection is non-empty in the fixture, so a kind wired to the WRONG
        // collection (or to none at all) cannot slip through by both sides reading 0.
        for (name, len, kind) in expected {
            assert!(len > 0, "fixture must populate `{name}` for this guard to mean anything");
            assert_eq!(
                v.count(kind) as usize,
                len,
                "core collection `{name}` holds {len} records but the FFI reports {} for {kind:?}",
                v.count(kind)
            );
        }
    }

    /// SCOPE OF THE "last opened" SIGNAL: a READ-ONLY open does not refresh
    /// `last_opened_at` (vault.rs skips the open-time save when `read_only`), so any
    /// number of read-only opens leave the reported previous-access stamp unchanged.
    /// Mobile is read-only-only and the desktop defaults to read-only, so this pins
    /// what the banner can and cannot detect: unauthorised WRITES, not reads.
    #[test]
    fn read_only_opens_do_not_advance_previous_access() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let first = open_full(&dir).previous_access();
        std::thread::sleep(std::time::Duration::from_millis(1100)); // cross a 1-second tick
        let second = open_full(&dir).previous_access();
        assert_eq!(
            first, second,
            "a read-only open left no trace: previous_access did not advance ({first} -> {second})"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    /// A never-opened vault must read "never", not a 1970 epoch date, which would
    /// look like a real (and alarming) prior access to the user.
    #[test]
    fn format_time_renders_never_for_a_zero_or_negative_stamp() {
        assert_eq!(format_time(0), "never");
        assert_eq!(format_time(-1), "never");
        assert_eq!(format_time(i64::MIN), "never");
        // A known instant: 2021-01-01T00:00:00Z.
        assert_eq!(format_time(1_609_459_200), "2021-01-01 00:00:00 UTC");
    }

    #[test]
    fn generation_rises_across_saves() {
        let dir = tmp();
        let path = dir.join("vault.pmv");
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        let mut ov = OpenVault::create(path, b"one", b"two", params).unwrap();
        ov.save().unwrap();
        ov.save().unwrap();
        let saved_gen = ov.vault.generation;
        drop(ov);
        let v = open_full_dir(&dir, b"one", b"two");
        assert_eq!(v.generation(), saved_gen, "FFI reports the last-saved generation");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn empty_kinds_list_empty() {
        let dir = tmp();
        make_vault(&dir, b"one", b"two");
        let v = open_full(&dir);
        assert_eq!(v.count(RecordKind::TrustWill), 0);
        assert_eq!(v.count(RecordKind::AssetLiability), 0);
        assert_eq!(v.count(RecordKind::RealEstate), 0);
        assert!(v.list_records(RecordKind::TrustWill).is_empty());
        assert!(v.list_records(RecordKind::AssetLiability).is_empty());
        assert!(v.list_records(RecordKind::RealEstate).is_empty());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn wrong_password_order_is_rejected() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let e = open_vault(dir.to_str().unwrap().to_string(), b"two".to_vec(), b"one".to_vec())
            .err()
            .expect("swapped passwords must fail");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn corrupt_vault_file_is_indistinguishable_from_wrong_password() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let path = dir.join("vault.pmv");
        let mut bytes = std::fs::read(&path).unwrap();
        let i = bytes.len() - 1;
        bytes[i] ^= 0xff;
        std::fs::write(&path, &bytes).unwrap();

        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("a corrupt vault must fail to open");
        assert!(
            matches!(e, VaultError::WrongPasswordOrCorrupt),
            "corruption maps to the same no-leak variant as a wrong password, got {e:?}"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn truncated_vault_file_maps_to_wrong_password_or_corrupt() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let path = dir.join("vault.pmv");
        std::fs::write(&path, b"PMV").unwrap();

        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("a truncated vault must fail to open");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt), "got {e:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn oversize_vault_file_maps_to_wrong_password_or_corrupt_not_internal() {
        // An oversize (padded) vault file is a tamper/corruption signal reachable on
        // the open path (read_capped_vault's size cap). It must collapse to the same
        // no-leak variant as every other open failure — never the distinct `Internal`.
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let path = dir.join("vault.pmv");
        // Grow the file past MAX_VAULT_SIZE (256 MiB) sparsely (set_len doesn't allocate).
        let f = std::fs::OpenOptions::new().write(true).open(&path).unwrap();
        f.set_len(256 * 1024 * 1024 + 1).unwrap();
        drop(f);
        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("an oversize vault must fail to open");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt), "got {e:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn bad_magic_maps_to_wrong_password_or_corrupt() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let path = dir.join("vault.pmv");
        let mut bytes = std::fs::read(&path).unwrap();
        bytes[0] ^= 0xff;
        std::fs::write(&path, &bytes).unwrap();

        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("bad magic must fail to open");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt), "got {e:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn missing_dir_with_other_files_present_still_not_found() {
        let dir = tmp();
        std::fs::write(dir.join("unrelated.txt"), b"hi").unwrap();
        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("no vault file => error");
        assert!(matches!(e, VaultError::NotFound), "got {e:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn reopen_after_close_sees_the_same_records() {
        let dir = tmp();
        let ids = make_full_vault(&dir, b"one", b"two");
        {
            let v = open_full(&dir);
            assert_eq!(v.count(RecordKind::Account), 1);
            drop(v);
        }
        let v2 = open_full(&dir);
        assert_eq!(v2.count(RecordKind::Account), 1);
        assert_eq!(v2.get_real_estate(ids.re.clone()).unwrap().address, "123 Main St");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn list_record_ids_match_typed_getters() {
        let dir = tmp();
        make_full_vault(&dir, b"one", b"two");
        let v = open_full(&dir);

        let ins_id = v.list_records(RecordKind::Instruction)[0].id.clone();
        assert_eq!(v.get_instruction(ins_id.clone()).unwrap().id, ins_id);
        let tw_id = v.list_records(RecordKind::TrustWill)[0].id.clone();
        assert_eq!(v.get_trust_will(tw_id.clone()).unwrap().id, tw_id);
        let asset_id = v.list_records(RecordKind::AssetLiability)[0].id.clone();
        assert_eq!(v.get_asset(asset_id.clone()).unwrap().id, asset_id);
        let acc_id = v.list_records(RecordKind::Account)[0].id.clone();
        assert_eq!(v.get_account(acc_id.clone()).unwrap().id, acc_id);
        let re_id = v.list_records(RecordKind::RealEstate)[0].id.clone();
        assert_eq!(v.get_real_estate(re_id.clone()).unwrap().id, re_id);
        std::fs::remove_dir_all(&dir).ok();
    }
    use vaultis_core::crypto::KdfParams;

    /// Build a small vault on disk with the core API, then return its directory.
    fn make_vault(dir: &std::path::Path, pw1: &[u8], pw2: &[u8]) {
        let path = dir.join("vault.pmv");
        // Cheap KDF params so the test is fast.
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        let mut ov = OpenVault::create(path, pw1, pw2, params).unwrap();
        let mut acc = records::Account::new().unwrap();
        acc.account_type = "Financial".into();
        acc.username = "alice".into();
        acc.password = "s3cret".into();
        records::upsert(&mut ov.vault.accounts, acc);
        let mut ins = records::Instruction::new().unwrap();
        ins.title = "Funeral wishes".into();
        records::upsert(&mut ov.vault.instructions, ins);
        ov.save().unwrap();
    }

    fn tmp() -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!(
            "pmffi-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn open_browse_and_view() {
        let dir = tmp();
        make_vault(&dir, b"one", b"two");

        let v = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .expect("opens with correct passwords");

        assert_eq!(v.count(RecordKind::Account), 1);
        assert_eq!(v.count(RecordKind::Instruction), 1);
        assert_eq!(v.count(RecordKind::RealEstate), 0);

        let accounts = v.list_records(RecordKind::Account);
        assert_eq!(accounts.len(), 1);
        assert_eq!(accounts[0].label, "Financial - alice");

        let acc = v.get_account(accounts[0].id.clone()).unwrap();
        assert_eq!(acc.username, "alice");
        assert_eq!(acc.password, "s3cret");

        // history exists (a "created" entry) and is fetched separately.
        let hist = v.get_history(RecordKind::Account, accounts[0].id.clone()).unwrap();
        assert!(!hist.is_empty());

        assert!(v.get_account("nope".into()).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn wrong_password_and_corrupt_are_indistinguishable() {
        let dir = tmp();
        make_vault(&dir, b"one", b"two");

        // Wrong password -> generic error.
        let e = open_vault(dir.to_str().unwrap().to_string(), b"bad".to_vec(), b"two".to_vec())
            .err()
            .expect("open should fail");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt));

        // Right passwords still open.
        assert!(
            open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec()).is_ok()
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn missing_vault_reports_not_found() {
        let dir = tmp();
        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("open should fail");
        assert!(matches!(e, VaultError::NotFound));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn previous_access_is_a_real_timestamp_not_a_constant() {
        // Kills the `previous_access -> 1` mutant: after create+save+reopen the
        // prior last-opened time is a real unix timestamp, never a small constant.
        let dir = tmp();
        make_vault(&dir, b"one", b"two");
        let v = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec()).unwrap();
        assert!(
            v.previous_access() > 1_000_000_000,
            "previous_access should be a real unix timestamp, got {}",
            v.previous_access()
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn recovery_notice_is_some_after_mirror_recovery() {
        // Kills the `recovery_notice -> None` mutant: with in-place redundancy on and
        // the primary vault.pmv corrupted, a read-only FFI open recovers from the
        // intact same-generation mirror and reports a recovery notice.
        let dir = tmp();
        let path = dir.join("vault.pmv");
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        {
            let mut ov = OpenVault::create(path.clone(), b"one", b"two", params).unwrap();
            ov.set_redundancy(1).unwrap();
            let mut ins = records::Instruction::new().unwrap();
            ins.title = "keep".into();
            records::upsert(&mut ov.vault.instructions, ins);
            ov.save().unwrap();
        } // drop releases the writer lock; save wrote the mirror
        // Flip the last byte (inside the Poly1305 tag) of the primary so its AEAD
        // fails while the same-generation mirror stays intact.
        let mut bytes = std::fs::read(&path).unwrap();
        let n = bytes.len();
        bytes[n - 1] ^= 0xff;
        std::fs::write(&path, &bytes).unwrap();

        let v = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .expect("FFI open recovers from the mirror");
        assert!(v.recovery_notice().is_some(), "FFI open should report recovery from the mirror");
        std::fs::remove_dir_all(&dir).ok();
    }
}
