//! vaultis-ffi — the UniFFI boundary that lets the Compose Multiplatform mobile
//! app drive the audited [`vaultis_core`] vault without reimplementing any
//! crypto, storage, or recovery logic.
//!
//! # What this crate is
//!
//! A *thin, additive* wrapper. The security-critical core (two-password Argon2id
//! KDF, XChaCha20-Poly1305, the partitioned crash-safe volume/manifest format,
//! and the corruption-fails-closed recovery) lives in `vaultis-core` and is
//! reused **verbatim**. This crate only:
//!   * holds an opaque, mutex-guarded [`OpenVault`] behind a UniFFI interface,
//!   * exposes flat value DTOs (Kotlin/Swift data classes) for the eight record
//!     types, and
//!   * maps the rich [`CoreVaultError`] down to a small, stable, **no-leak**
//!     [`VaultError`] (wrong-password and corrupt both collapse to one variant,
//!     exactly like the desktop's generic "can't open" message).
//!
//! # v1 scope — READ-ONLY
//!
//! Open with the two passwords, browse all eight tabs, view a record, read its
//! edit history. No create/edit/delete/documents/rekey yet (those are additive
//! follow-ups). A read-only open writes nothing to disk and never takes the
//! single-writer lock.
//!
//! # Security downgrade (disclosed)
//!
//! Returning a record DTO copies its fields — including a cleartext password —
//! into the JVM/Swift heap, where `ZeroizeOnDrop` cannot reach and the GC/ARC
//! may duplicate the bytes. This is an inherent, documented downgrade versus the
//! desktop. The host must minimise copies, fetch history explicitly (it can
//! contain old/new passwords), and clear clipboard/fields itself.
//!
//! The Rust side is also imperfect here, by construction: the `#[derive(uniffi::Record)]`
//! DTOs (e.g. [`Account::password`], [`Change::detail`]) and the `RustBuffer` UniFFI
//! lowers them into are NOT zeroize-on-drop. (They cannot be: UniFFI lowers a record
//! by *moving its fields out*, which Rust forbids for any type with a `Drop` impl —
//! so a `ZeroizeOnDrop` DTO would not compile.) So a `get_account`/`get_history` call
//! leaves short-lived cleartext copies in freed Rust heap in addition to the host
//! copy above. The core records themselves remain `ZeroizeOnDrop`; only these
//! boundary DTOs are exempt. Treat process memory as sensitive after a record read.

// NOTE: this crate intentionally does NOT `#![forbid(unsafe_code)]` — the UniFFI
// scaffolding generated by `setup_scaffolding!()` contains `unsafe`. The core,
// which holds all the real logic, keeps its crate-wide `forbid`.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use vaultis_core::records::{self, Record};
use vaultis_core::vault::{OpenVault, VaultError as CoreVaultError};
use zeroize::Zeroizing;

uniffi::setup_scaffolding!();

// ---------------------------------------------------------------------------
// Error: a small, stable, no-leak surface mapped from CoreVaultError.
// ---------------------------------------------------------------------------

/// Stable error surface for the mobile host. Crucially, a wrong password and a
/// corrupt/tampered vault collapse to the SAME [`VaultError::WrongPasswordOrCorrupt`]
/// variant with no detail, so the FFI never becomes a correct-password oracle —
/// mirroring the desktop's single generic failure message.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum VaultError {
    /// The two passwords were wrong, OR the vault file is corrupt/tampered. These
    /// are deliberately indistinguishable (no leak). Re-check both passwords and
    /// their order first.
    #[error("wrong passwords, or the vault is corrupt")]
    WrongPasswordOrCorrupt,
    /// No vault file exists at the given location.
    #[error("no vault found at the given location")]
    NotFound,
    /// An interrupted password change is pending; it must be finished on a
    /// writable (desktop) open before the vault can be read here.
    #[error("an interrupted password change is pending; finish it on desktop (--write)")]
    RekeyPending,
    /// Another writable session holds the vault (should not occur for read-only).
    #[error("the vault is open in another session")]
    Locked,
    /// No record with the requested id exists in that tab.
    #[error("record not found")]
    RecordNotFound,
    /// A low-level I/O error touching the vault directory.
    #[error("I/O error")]
    Io,
    /// An unexpected internal error.
    #[error("internal error")]
    Internal,
}

impl From<CoreVaultError> for VaultError {
    fn from(e: CoreVaultError) -> Self {
        match e {
            CoreVaultError::NotFound(_) => VaultError::NotFound,
            CoreVaultError::RekeyPending => VaultError::RekeyPending,
            CoreVaultError::Locked => VaultError::Locked,
            CoreVaultError::Io(_) => VaultError::Io,
            // Everything that could discriminate a wrong password from a damaged
            // vault collapses to ONE generic variant so there is no correct-password
            // oracle: the AEAD decrypt failure, bad magic/version/params, a truncated
            // file, a JSON/storage decode failure — AND `ArchiveMismatch`. The latter
            // is only reachable AFTER decrypt_with_redundancy succeeds (i.e. only with
            // the CORRECT passwords), so giving it a distinct variant let a
            // dir-write attacker turn the open into a binary correct-password oracle by
            // pre-deleting a referenced blob (audit R-3). Folding it here restores the
            // no-oracle contract. (RekeyPending is fine: it is returned BEFORE any
            // decryption, so it fires for any password and leaks nothing.)
            CoreVaultError::Crypto(_)
            | CoreVaultError::BadMagic
            | CoreVaultError::BadVersion(_)
            | CoreVaultError::Truncated
            | CoreVaultError::BadParams
            | CoreVaultError::Json(_)
            | CoreVaultError::ArchiveMismatch
            // `TooLarge` IS reachable on the open path: `read_capped_vault` rejects a
            // vault file > MAX_VAULT_SIZE BEFORE decryption. An oversize file is a
            // corruption/tamper signal, so it must collapse here too — otherwise a
            // padded vault would return a distinct `Internal`, breaking the "every open
            // failure looks identical" property (it is password-independent, so not a
            // password oracle, but folding it keeps the surface uniform).
            | CoreVaultError::TooLarge
            | CoreVaultError::Storage(_) => VaultError::WrongPasswordOrCorrupt,
            // Genuinely unreachable on a read-only open (create/write/doc-read only),
            // mapped defensively to a generic internal error.
            CoreVaultError::AlreadyExists(_)
            | CoreVaultError::ReadOnly
            | CoreVaultError::StillReferenced
            | CoreVaultError::NoSuchPartition(_) => VaultError::Internal,
        }
    }
}

// ---------------------------------------------------------------------------
// Value DTOs — flat mirrors of the eight records.rs structs (read views).
// History is NOT bundled (it can embed old/new passwords); fetch it explicitly.
// ---------------------------------------------------------------------------

/// Which tab / record collection to operate on — all EIGHT the core stores.
///
/// The v1 surface deliberately exposed only five, which silently hid three
/// collections from the mobile viewer with nothing on screen to say so. `Urgent` is
/// the worst of the three to hide: the core documents it as "Tab 0 … the most
/// time-critical things an executor must know (whom to call, where the safe key is,
/// an in-flight crisis) are the first thing seen on unlock". An executor reaching for
/// a phone in exactly that situation saw a complete-looking app with no urgent note in
/// it. Ordered to match the desktop's tab order.
#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum RecordKind {
    Urgent,
    Instruction,
    TrustWill,
    AssetLiability,
    Account,
    RealEstate,
    TaxFiling,
    GeneralDocument,
}

/// One row in a tab's master list.
#[derive(uniffi::Record)]
pub struct RecordSummary {
    pub id: String,
    /// Human label (same logic the desktop list uses).
    pub label: String,
}

/// One timestamped history / audit entry. `detail` MAY contain cleartext old/new
/// field values (including passwords) by design — gate/redact on the host.
#[derive(uniffi::Record)]
pub struct Change {
    pub at: i64,
    pub action: String,
    pub detail: String,
}

/// An URGENT note — the executor's "read this first" collection (core tab 0).
/// Field-identical to [`Instruction`], but a separate, prominent collection.
#[derive(uniffi::Record)]
pub struct Urgent {
    pub id: String,
    pub title: String,
    pub description: String,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct Instruction {
    pub id: String,
    pub title: String,
    pub description: String,
    pub created_at: i64,
    pub updated_at: i64,
}

/// One tax filing year. `documents` lists the volume file ids attached to the year;
/// the host cannot open them yet, but it MUST be able to see that they exist.
#[derive(uniffi::Record)]
pub struct TaxFiling {
    pub id: String,
    pub owner: String,
    pub year: String,
    pub notes: String,
    /// How many documents are attached (the ids themselves are not useful to the
    /// host until document export exists, but the count must not be hidden).
    pub document_count: u32,
    pub created_at: i64,
    pub updated_at: i64,
}

/// A general document entry (title + description + at most one attached file).
#[derive(uniffi::Record)]
pub struct GeneralDocument {
    pub id: String,
    pub title: String,
    pub description: String,
    /// Volume file id of the attached document, if any (opening it is post-MVP).
    pub file: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct TrustWill {
    pub id: String,
    pub document: String,
    pub usage: String,
    /// Volume file id of an attached document, if any (opening it is post-MVP).
    pub file: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct AssetLiability {
    pub id: String,
    pub kind: String,
    pub description: String,
    pub owner: String,
    pub title: String,
    pub approx_value: String,
    pub as_of_date: String,
    pub institution: String,
    pub asset_type: String,
    pub url: String,
    pub beneficiary: String,
    pub review: bool,
    pub statement: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct Account {
    pub id: String,
    pub title: String,
    pub account_type: String,
    pub account_subtype: String,
    pub owner: String,
    pub username: String,
    /// Cleartext. Crosses into the JVM/Swift heap — see the crate-level note.
    pub password: String,
    pub description: String,
    pub url: String,
    /// Date the account was closed (`YYYY-MM-DD`); blank while open.
    pub closed_as_of: String,
    pub review: bool,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct RealEstate {
    pub id: String,
    pub address: String,
    pub ownership: String,
    pub taxes: String,
    pub hoa: String,
    pub income_account: String,
    pub financing_account: String,
    pub payment_account: String,
    pub created_at: i64,
    pub updated_at: i64,
}

// --- core -> DTO mappers ---------------------------------------------------

fn map_change(c: &records::Change) -> Change {
    // Mask secret (password) before/after values via the core's audited helper, so the
    // FFI never ships cleartext old/new passwords across the boundary. `detail` for a
    // password field is `password: "old" -> "new"`; `display_detail` rewrites it to
    // `password: <hidden> -> <hidden>` and passes every non-secret detail through
    // unchanged (audit-log entries hold no passwords, so this is a no-op for them).
    Change { at: c.at, action: c.action.clone(), detail: records::display_detail(&c.detail) }
}

fn map_urgent(r: &records::Urgent) -> Urgent {
    Urgent {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_instruction(r: &records::Instruction) -> Instruction {
    Instruction {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_tax_filing(r: &records::TaxFiling) -> TaxFiling {
    TaxFiling {
        id: r.id.clone(),
        owner: r.owner.clone(),
        year: r.year.clone(),
        notes: r.notes.clone(),
        // `as u32` is safe: the document count is bounded by the store's own caps,
        // far below u32::MAX, and a saturating cast keeps a corrupt count from wrapping.
        document_count: u32::try_from(r.documents.len()).unwrap_or(u32::MAX),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_general_document(r: &records::GeneralDocument) -> GeneralDocument {
    GeneralDocument {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        file: r.file.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_trust_will(r: &records::TrustWill) -> TrustWill {
    TrustWill {
        id: r.id.clone(),
        document: r.document.clone(),
        usage: r.usage.clone(),
        file: r.file.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_asset(r: &records::AssetLiability) -> AssetLiability {
    AssetLiability {
        id: r.id.clone(),
        kind: r.kind.clone(),
        description: r.description.clone(),
        owner: r.owner.clone(),
        title: r.title.clone(),
        approx_value: r.approx_value.clone(),
        as_of_date: r.as_of_date.clone(),
        institution: r.institution.clone(),
        asset_type: r.asset_type.clone(),
        url: r.url.clone(),
        beneficiary: r.beneficiary.clone(),
        review: r.review,
        statement: r.statement.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_account(r: &records::Account) -> Account {
    Account {
        id: r.id.clone(),
        title: r.title.clone(),
        account_type: r.account_type.clone(),
        account_subtype: r.account_subtype.clone(),
        owner: r.owner.clone(),
        username: r.username.clone(),
        password: r.password.clone(),
        description: r.description.clone(),
        url: r.url.clone(),
        closed_as_of: r.closed_as_of.clone(),
        review: r.review,
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_real_estate(r: &records::RealEstate) -> RealEstate {
    RealEstate {
        id: r.id.clone(),
        address: r.address.clone(),
        ownership: r.owner.clone(),
        taxes: r.taxes.clone(),
        hoa: r.hoa.clone(),
        income_account: r.income_account.clone(),
        financing_account: r.financing_account.clone(),
        payment_account: r.payment_account.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

// ---------------------------------------------------------------------------
// The opaque unlocked-vault handle.
// ---------------------------------------------------------------------------

/// An unlocked vault. Opaque to the host: the derived key never crosses the FFI.
/// Wraps the core [`OpenVault`] behind a mutex so the host can hold exactly one
/// handle and every call is serialised (this stands in for the desktop's
/// cross-process single-writer file lock, which a single app process doesn't
/// need). Dropping the handle runs the core's zeroize-on-drop.
#[derive(uniffi::Object)]
pub struct Vault {
    inner: Mutex<OpenVault>,
}

/// Open an existing vault **read-only** with the two passwords, in order.
///
/// `dir` is the app-private directory that holds `vault.pmv` (+ `manifest/`,
/// `volume/`) — the host hands in its sandbox path; arbitrary user paths are not
/// accepted. `pw1`/`pw2` are the raw password bytes. UniFFI lowers the host's
/// ByteArray/Data into Rust-OWNED `Vec<u8>` copies, so this function wipes them
/// before returning — on success, on the error path, AND on an unwind if the open
/// path ever panics; the host should still overwrite its own copies afterwards.
#[uniffi::export]
pub fn open_vault(dir: String, pw1: Vec<u8>, pw2: Vec<u8>) -> Result<Arc<Vault>, VaultError> {
    // Bind the host-owned plaintext copies in `Zeroizing` so they are wiped on EVERY
    // exit, including a panic-unwind. A plain `.zeroize()` AFTER the open call is
    // skipped by unwinding, which would strand the master passwords in freed heap.
    let pw1 = Zeroizing::new(pw1);
    let pw2 = Zeroizing::new(pw2);
    let path = PathBuf::from(dir).join("vault.pmv");
    let opened = OpenVault::open_read_only(path, &pw1, &pw2)?;
    Ok(Arc::new(Vault { inner: Mutex::new(opened) }))
}

#[uniffi::export]
impl Vault {
    /// Human-readable notice if the live `vault.pmv` was unreadable and the vault
    /// was recovered from an in-place redundant copy (a roll-forward/rollback);
    /// `None` on a normal open. Surface it so the user is rollback-aware.
    pub fn recovery_notice(&self) -> Option<String> {
        self.lock().recovery_notice().map(|s| s.to_string())
    }

    /// The monotonic write counter of the snapshot just opened. A surprise drop
    /// versus a remembered value signals a whole-file rollback to an older copy.
    pub fn generation(&self) -> u64 {
        self.lock().opened_generation()
    }

    /// Unix-seconds timestamp the vault was previously opened (0 if never).
    pub fn previous_access(&self) -> i64 {
        self.lock().previous_access()
    }

    /// [`Vault::previous_access`] rendered exactly like the desktop's `format_time`:
    /// `YYYY-MM-DD HH:MM:SS UTC`, or `"never"` for a zero/negative stamp.
    ///
    /// The host shows this on unlock so an access the user does not recognise is
    /// visible — the same unauthorised-open signal both desktop front-ends print
    /// ("Unlocked. Last opened: … (generation N)"). Formatting lives here, not in
    /// Kotlin/Swift, so the (fiddly) calendar math stays in the one audited
    /// implementation (`vaultis_core::records::civil_from_unix`) and cannot drift
    /// between the desktop and the two mobile front-ends.
    pub fn previous_access_label(&self) -> String {
        format_time(self.lock().previous_access())
    }

    /// The master list for one tab: `{id, label}` per record, in stored order.
    pub fn list_records(&self, kind: RecordKind) -> Vec<RecordSummary> {
        let ov = self.lock();
        let v = &ov.vault;
        match kind {
            RecordKind::Urgent => v.urgent.iter().map(summary).collect(),
            RecordKind::Instruction => v.instructions.iter().map(summary).collect(),
            RecordKind::TrustWill => v.trust_wills.iter().map(summary).collect(),
            RecordKind::AssetLiability => v.assets.iter().map(summary).collect(),
            RecordKind::Account => v.accounts.iter().map(summary).collect(),
            RecordKind::RealEstate => v.real_estate.iter().map(summary).collect(),
            RecordKind::TaxFiling => v.tax_filings.iter().map(summary).collect(),
            RecordKind::GeneralDocument => v.general_documents.iter().map(summary).collect(),
        }
    }

    /// How many records are in a tab (cheap, no cleartext crosses the boundary).
    pub fn count(&self, kind: RecordKind) -> u32 {
        let ov = self.lock();
        let v = &ov.vault;
        let n = match kind {
            RecordKind::Urgent => v.urgent.len(),
            RecordKind::Instruction => v.instructions.len(),
            RecordKind::TrustWill => v.trust_wills.len(),
            RecordKind::AssetLiability => v.assets.len(),
            RecordKind::Account => v.accounts.len(),
            RecordKind::RealEstate => v.real_estate.len(),
            RecordKind::TaxFiling => v.tax_filings.len(),
            RecordKind::GeneralDocument => v.general_documents.len(),
        };
        n as u32
    }

    pub fn get_urgent(&self, id: String) -> Result<Urgent, VaultError> {
        let ov = self.lock();
        ov.vault
            .urgent
            .iter()
            .find(|r| r.id == id)
            .map(map_urgent)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_instruction(&self, id: String) -> Result<Instruction, VaultError> {
        let ov = self.lock();
        ov.vault
            .instructions
            .iter()
            .find(|r| r.id == id)
            .map(map_instruction)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_tax_filing(&self, id: String) -> Result<TaxFiling, VaultError> {
        let ov = self.lock();
        ov.vault
            .tax_filings
            .iter()
            .find(|r| r.id == id)
            .map(map_tax_filing)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_general_document(&self, id: String) -> Result<GeneralDocument, VaultError> {
        let ov = self.lock();
        ov.vault
            .general_documents
            .iter()
            .find(|r| r.id == id)
            .map(map_general_document)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_trust_will(&self, id: String) -> Result<TrustWill, VaultError> {
        let ov = self.lock();
        ov.vault
            .trust_wills
            .iter()
            .find(|r| r.id == id)
            .map(map_trust_will)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_asset(&self, id: String) -> Result<AssetLiability, VaultError> {
        let ov = self.lock();
        ov.vault
            .assets
            .iter()
            .find(|r| r.id == id)
            .map(map_asset)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_account(&self, id: String) -> Result<Account, VaultError> {
        let ov = self.lock();
        ov.vault
            .accounts
            .iter()
            .find(|r| r.id == id)
            .map(map_account)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_real_estate(&self, id: String) -> Result<RealEstate, VaultError> {
        let ov = self.lock();
        ov.vault
            .real_estate
            .iter()
            .find(|r| r.id == id)
            .map(map_real_estate)
            .ok_or(VaultError::RecordNotFound)
    }

    /// A record's edit history, newest concerns last. Fetched explicitly (never bundled
    /// into the record DTO). Secret (password) before/after values are MASKED here via
    /// the core's `display_detail` (see `map_change`), so no cleartext password ever
    /// crosses the FFI boundary; the host may still choose to gate the whole history.
    pub fn get_history(&self, kind: RecordKind, id: String) -> Result<Vec<Change>, VaultError> {
        let ov = self.lock();
        let v = &ov.vault;
        let history = match kind {
            RecordKind::Urgent => v.urgent.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::Instruction => v.instructions.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::TrustWill => v.trust_wills.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::AssetLiability => v.assets.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::Account => v.accounts.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::RealEstate => v.real_estate.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::TaxFiling => v.tax_filings.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::GeneralDocument => v.general_documents.iter().find(|r| r.id == id).map(|r| &r.history),
        };
        history
            .map(|h| h.iter().map(map_change).collect())
            .ok_or(VaultError::RecordNotFound)
    }

    /// The vault-wide audit log (created/deleted/opened/compacted events).
    pub fn audit_log(&self) -> Vec<Change> {
        self.lock().vault.audit.iter().map(map_change).collect()
    }
}

impl Vault {
    /// Lock the inner handle, recovering from a poisoned mutex (a panic in a
    /// previous call) by taking the guard anyway — the core data is still valid
    /// and there is only one handle, so there is nothing to corrupt.
    fn lock(&self) -> std::sync::MutexGuard<'_, OpenVault> {
        self.inner.lock().unwrap_or_else(|p| p.into_inner())
    }
}

fn summary<R: Record>(r: &R) -> RecordSummary {
    RecordSummary { id: r.id().to_string(), label: r.label() }
}

/// Format a unix-seconds timestamp as `YYYY-MM-DD HH:MM:SS UTC`, or `"never"` for a
/// zero/negative stamp. Byte-for-byte the desktop's `format_time` (vaultis-desktop
/// `ui.rs`), including the shared `civil_from_unix` calendar math, so the "last
/// opened" line the mobile host shows is identical to the desktop's.
fn format_time(ts: i64) -> String {
    if ts <= 0 {
        return "never".to_string();
    }
    let (year, mo, d, h, m, s) = records::civil_from_unix(ts);
    format!("{year:04}-{mo:02}-{d:02} {h:02}:{m:02}:{s:02} UTC")
}

// ---------------------------------------------------------------------------
// Host-side tests: drive the FFI surface against a real vault built with the
// core (no Android/iOS toolchain needed). Verifies open/list/get/history + the
// no-leak error mapping.
// ---------------------------------------------------------------------------
#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;
